### ISSUE TITLE
Authenticating in sample project results in a connection error

### ISSUE THREAD

**Issue by gcurtis** [box/box-android-content-sdk#2]
I tried running the sample project, but I keep getting a connection error after logging in:

![Screenshot of authentication error](http://i.imgur.com/UCxwQrJ.png)

Does the sample project expect a specific redirect URI to be set in my application's settings?

**Comment by cpore** [comment]
I'm having this issue as well. Apologies, I don't have much more information, but the app doesn't seem to be handling the authentication response.

**Comment by doncung** [comment]
You can solve this by specifying the static redirect url. 
BoxConfig.REDIRECT_URL = "https://localhost";

Generally it was intended for you to use these static config variables instead of BoxSession constructor that takes a client id and secret which was intended for the advanced use case of the application needing to dynamically handle multiple api keys.

**Comment by gcurtis** [comment]
@doncung I think it would help a lot if we added a comment in the sample app telling the developer what their redirect URI should be. It'd be even better if we could detect an incorrect redirect URI and show a helpful error message with instructions on how to fix it.

**Comment by MariusVolkhart** [comment]
Setting `BoxConfig.REDIRECT_URL = "https://localhost";` does not work. I get this as a response. The first blacked-out section is my client id

![screenshot_2015-05-05-15-05-22](https://cloud.githubusercontent.com/assets/1709517/7497623/4b2cc7fa-f3e1-11e4-8e35-014293e63ada.png)

**Comment by doncung** [comment]
Sorry should have been more clear. BoxConfig.REDIRECT_URL must match
exactly whar redirect url was set in your developers settings. The previous
poster had it set to https://localhost.

**Comment by MariusVolkhart** [comment]
@doncung awesome that works. thanks!

**Comment by doncung** [comment]
Added additional documentation for setting the redirect url and added it to the initial launch of the web view.
